upload:
	curl -F file=@/path/to/man.jpg "http://127.0.0.1:8888/face_images/man.jpg?collection=face_images"

download:
	curl -o man.jpg "http://127.0.0.1:8888/face_images/man.jpg?collection=face_images"
